package com.teamechoes.echoesoftheconvergence.objects;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import org.json.JSONObject;
import org.json.JSONPropertyIgnore;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBIgnore;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.teamechoes.echoesoftheconvergence.interfaces.DynamoObject;

import lombok.Data;

@Data
@DynamoDBTable(tableName="accounts")
public class Account extends DynamoObject{
	@DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
	String id;
	
	@DynamoDBRangeKey
	String username;
	
	String password, email, creation;
	
	public Account() {
		
	}

	public Account(JSONObject jo) {
		super(jo);
	}
	
	//system should be set to UTC
	public String getCreation() {
		return creation;
	}
	
	public void setCreation(String creation) {
		this.creation = creation;
	}
	
	@DynamoDBIgnore
	@JSONPropertyIgnore
	public LocalDateTime getCreationAsLocalDateTime() {
		return LocalDateTime.parse(creation, DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
	}
	
	@DynamoDBIgnore
	public void setCreation(LocalDateTime creation) {
		this.creation = creation.format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));
	}
}
