package com.teamechoes.echoesoftheconvergence.objects;

import java.util.Set;

import org.json.JSONObject;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.teamechoes.echoesoftheconvergence.interfaces.DynamoObject;

import lombok.Data;

@Data
@DynamoDBTable(tableName="ships")
public class Ship extends DynamoObject{
	@DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
	String id;
	
	String owner_id, name;
	Set<String> rooms;
	
	public Ship() {
		
	}

	public Ship(JSONObject jo) {
		super(jo);
	}
}
